# จำนวน Epochs ในการเทรน
EPOCHS: 5
# จำนวนข้อมูลต่อรอบการเทรน
BATCH_SIZE: 1024
# การขยายข้อมูล (สำหรับตารางมักเป็น False หรือไม่ต้องใส่)
AUGMENTATION: False
# สำคัญ: จำนวนคอลัมน์ Feature ใน CSV ของคุณ (เช่น 7)
NUM_FEATURES: [13]
# อัตราการเรียนรู้ของโมเดล
LEARNING_RATE: 0.01
# พารามิเตอร์เดิมจาก VGG16 (เก็บไว้กันโค้ดพังแต่ไม่ได้ใช้ใน ANN)
SAMPLING_RATIO : 50
INCLUDE_TOP: False
WEIGHTS: imagenet
CLASSES: 1  # 1 สำหรับ Binary Classification (Fraud หรือไม่)